repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-yaml
- repo: https://github.com/pycqa/isort
  rev: 5.8.0
  hooks:
  - id: isort
    name: isort (python)
    args: ["--profile", "black"]
- repo: https://github.com/ambv/black
  rev: 21.7b0
  hooks:
  - id: black
    name: black formatting (python)
- repo: local
  hooks:
  - id: pylint
    name: pylint
    language: system
    entry: poetry run pylint
    args: ["--ignore-paths=tests/*"]
    types: [python]
  - id: pytest
    name: pytest
    language: system
    entry: poetry run pytest --doctest-modules ./tests
    types: [python]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    additional_dependencies:
      - types-requests
      - types-toml
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    additional_dependencies:
      - toml
